name = "turboSHFmk"
chain = "mainnet"
address = "0x7a3A49042aE1A2020c69552d49BF5E11B666BfBF"

[calibers.mainnet]
address = "0xbeef3ccD0473F70D7e8e09997E1b270EAE197C44"
swapper = "0x923c98b22F9c367A109E93f7dfBaCa28b20C17C3"
rootfiles = "github:MakinaHQ/makina-test-integrations/machines/turboSHFmk/mainnet/rootfiles"

[calibers.mainnet.accounting_token]
address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
decimals = 6
name = "USD Coin"
symbol = "USDC"

[calibers.arbitrum]
address = "0xbeef3ccD0473F70D7e8e09997E1b270EAE197C44"
swapper = "0x923c98b22F9c367A109E93f7dfBaCa28b20C17C3"
rootfiles = "github:MakinaHQ/makina-test-integrations/machines/turboSHFmk/arbitrum/rootfiles"

[calibers.arbitrum.accounting_token]
address = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
decimals = 6
name = "USD Coin"
symbol = "USDC"

[calibers.base]
address = "0xbeef3ccD0473F70D7e8e09997E1b270EAE197C44"
swapper = "0x923c98b22F9c367A109E93f7dfBaCa28b20C17C3"
rootfiles = "github:MakinaHQ/makina-test-integrations/machines/turboSHFmk/base/rootfiles"

[calibers.base.accounting_token]
address = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
decimals = 6
name = "USD Coin"
symbol = "USDC"