name = "tstUSDC2"
chain = "mainnet"
address = "0x42149F0a945952F80e462cA113fbDB8Ca71756c8"

[calibers.mainnet]
address = "0x690e587eD87D776793e98bDaD8f20B566999A44c"
swapper = "0xe403614F41554fC0f7A3dD581878D0024Dc978E9"
rootfiles = "github:MakinaHQ/makina-test-integrations/machines/tstUSDC2/mainnet/rootfiles"

[calibers.mainnet.accounting_token]
address = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
decimals = 6
name = "USD Coin"
symbol = "USDC"
